web:
  build: .
  ports:
    - "80:80"
  links:
    - mysql
  volumes:
    - $PWD/data/mageto-files:/var/www/htdocs/media
    - $PWD/data/wp-files:/var/www/htdocs/wp/wp-content/uploads
  env_file:
    - env
mysql:
  image: mysql:5.7
  volumes:
    - $PWD/data/mysql:/var/lib/mysql
  env_file:
    - env
